name: CI

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

permissions:
  contents: read

jobs:
  Test:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Get Secret Name
        id: name
        run: |
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value 'ss=secrets["Test"]'

      - name: Read Secret
        env:
          ss: ${{ steps.name.outputs.ss }}
        run: |
          $secret = $env:ss
          Write-Host "Secret lenght is $($secret.Count). Secret is $secret"
