name: CI

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

permissions:
  contents: read

jobs:
  Test:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Get Secret Name
        id: name
        run: |
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "secret='secrets[`"Test`"]'"

      - name: Read Secret
        run: |
          $secret = "${{ steps.name.outputs.secretName }}"
          Write-Host "Secret lenght is $($secret.Count). Secret is $secret"
